# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170507_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalassistant',
            name='image',
            field=models.ImageField(blank=True, default=b'photos/default_photo.jpg', upload_to=b'photos/'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='image',
            field=models.ImageField(blank=True, default=b'photos/default_photo.jpg', upload_to=b'photos/'),
        ),
        migrations.AddField(
            model_name='storeadmin',
            name='image',
            field=models.ImageField(blank=True, default=b'photos/default_photo.jpg', upload_to=b'photos/'),
        ),
    ]
