# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170520_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(b'Under Process', b'Under Process'), (b'Booked', b'Booked'), (b'Rejected', b'Rejected'), (b'Cancel', b'Cancel'), (b'Missed', b'Missed'), (b'Attended', b'Attended'), (b'Assigned', b'Assigned')], default=b'Under Process', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointmentship',
            name='status',
            field=models.CharField(choices=[(b'Under Process', b'Under Process'), (b'Booked', b'Booked'), (b'Rejected', b'Rejected'), (b'Cancel', b'Cancel'), (b'Missed', b'Missed'), (b'Attended', b'Attended'), (b'Assigned', b'Assigned')], default=b'Under Process', max_length=15),
        ),
    ]
